version: "1"

services:
  ftpservice:
    image: delfer/alpine-ftp-server
    hostname: ftpserver
    container_name: ftpserver
    ports:
      - "20-21:20-21"
      - "21000-21010:21000-21010"
    networks:
      - back-tier
    env_file: ./ftpserver/config.env
    expose:
      - "20-21"
      - "21000-21010"

  backendservice:
    image: php:8.1-apache
    hostname: php-back
    container_name: php-back
    volumes:
      - ./php-back:/var/www/html
    ports:
      - "127.0.0.1:8000:80"
    expose:
      - "80"
      - "8000"
    networks:
      - back-tier

  frontendservice:
    image: nginx
    hostname: frontend
    container_name: frontend
    ports:
      - "127.0.0.1:8080:80"
    expose:
      - 8080
    networks:
      - back-tier
    volumes:
      - ./frontend:/usr/share/nginx/html


    
networks:
  # The presence of these objects is sufficient to define them
  back-tier: {}